---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-mirrored-pair-volume.html
sidebar: sidebar
keywords: change, settings, mirrored, pair, volume, adjust, percentage, point, system, manager, alert, notification, reserved, capacity, full
summary: "You can change the settings for a mirrored pair volume to adjust the percentage point at which System Manager sends an alert notification when the reserved capacity for a mirrored pair volume is nearing full."
---
= Change the reserved capacity settings for a mirrored pair volume
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
You can change the settings for a mirrored pair volume to adjust the percentage point at which System Manager sends an alert notification when the reserved capacity for a mirrored pair volume is nearing full.

.Steps

. Select menu:Storage[Pools & Volume Groups].
. Select the *Reserved Capacity* tab.
. Select the mirrored pair volume that you want to edit, and then click *View/Edit Settings*.
+
The *Mirrored Pair Volume Reserved Capacity Settings* dialog box appears.

. Change the reserved capacity settings for the mirrored pair volume as appropriate.
+
.Field Details
[%collapsible]

====
[cols="1a,3a",options="header"]
|===
| Setting| Description
a|
Alert me when...
a|
Use the spinner box to adjust the percentage point at which System Manager sends an alert notification when the reserved capacity for a mirrored pair is nearing full.

When the reserved capacity for the mirrored pair exceeds the specified threshold, System Manager sends an alert, allowing you time to increase reserved capacity.

[NOTE]

Changing the Alert setting for one mirrored pair changes the Alert setting for all mirrored pairs that belong to the same mirror consistency group.
a|
Policy for full reserved capacity
a|
You can choose one of the following policies:

* *Purge oldest snapshot image* – System Manager automatically purges the oldest snapshot image in the consistency group, which releases the member's reserved capacity for reuse within the group.
* *Reject writes to base volume* – When the reserved capacity reaches its maximum defined percentage, System Manager rejects any I/O write request to the base volume that triggered the reserved capacity access.
|===
====
. Click *Save* to apply your changes.

.Result
System Manager changes the reserved capacity settings for the member volume, as well as the reserved capacity settings for all member volumes in the consistency group.
