---
settings:
  name: "SANtricity 116"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
sidebar:
  entries:
  - title: SANtricity docs
    url: "/index.html"
  - title: System Manager
    entries:
    - section: sm-storage
    - section: sm-mirroring
    - section: sm-hardware
    - section: sm-settings
    - section: sm-support
  - title: Unified Manager
    entries:
    - section: um-admin
    - section: um-manage
    - section: um-certificates
