---
permalink: sm-hardware/task_erase_drive.html
sidebar: sidebar
keywords: 
summary: 'You can erase a secure-enabled drive so it can be reused in another volume group, pool, SSD cache, or in another storage array. This procedure resets the drive’s security attributes and ensures that the data cannot be read again.'
---
= Erase secure-enabled drive
:icons: font
:imagesdir: ../media/

[.lead]
You can erase a secure-enabled drive so it can be reused in another volume group, pool, SSD cache, or in another storage array. This procedure resets the drive's security attributes and ensures that the data cannot be read again.

== Before you begin

The secure-enabled drive must be in an Unassigned state.

== About this task

Use the Secure Erase option only if you want to remove all data on a secure-enabled drive and reset the drive's security attributes.

[CAUTION]
====
*Possible loss of data* -- The Secure Erase operation cannot be undone. Make sure you select the correct drive during the procedure.
====

== Steps

. Select *Hardware*.
. If the graphic shows the controllers, click *Show front of shelf*.
+
The graphic changes to show the drives instead of the controllers.

. Use the filter fields to view all the secure-enabled, unassigned drives in the shelf. From the *Show drives that are...* drop-down lists, select *Secure-enabled* and *Unassigned*.
+
[NOTE]
====
+
====
+
If all drives share the same physical attributes, the *Show drives that are...* filter field does not appear. If all drives share the same logical attributes, the *Anywhere in the storage array* filter field does not appear.
+
The shelf view shows only the secure-enabled, unassigned drives; all others are grayed out.

. Select the secure-enabled drive you want to erase.
+
[CAUTION]
====
*Possible loss of data*-- Make sure that you have selected the correct drive. After completing the Secure Erase operation, you cannot recover any of the data.
====
+
The drive's context menu opens.

. Select *Secure Erase*.
+
The Secure Erase option only appears if you select an unassigned, secure-enabled drive.
+
[NOTE]
====
For NVMe SED drives, you must provide the PSID. You can find the PSID on the drive label. This is necessary if you do not have the backup lock key.
====

. In the Secure Erase Drive dialog box, read the important information about data loss.
. Confirm the operation, and then click *Erase*.

== Results

The drive is now available for use in another volume group or disk pool, or in another storage array.
