---
permalink: sm-settings/add-trap-destinations-for-snmp-alerts.html
sidebar: sidebar
keywords: ten server, snmp traps, sending
summary: "You can add up to 10 servers for sending SNMP traps."
---
= Add trap destinations for SNMP alerts
:icons: font
:imagesdir: ../media/

[.lead]
You can add up to 10 servers for sending SNMP traps.

.Before you begin

* The network server you want to add must be configured with an SNMP service application. You need the network address of this server (either an IPv4 or an IPv6 address), so the event monitor can send trap messages to that address. You can use more than one server (up to 10 servers are allowed).
* A community name must be created, consisting of only printable ASCII characters. The community name, which is a string that acts like a password for the network servers, is typically created by a network administrator. Up to 256 communities can be created.
* The management information base (MIB) file has been copied and compiled on the server with the SNMP service application. This MIB file defines the data being monitored and managed.
+
If you do not have the MIB file, you can obtain it from the NetApp Support site:

 ** Go to https://mysupport.netapp.com/site/[NetApp Support^].
 ** Click *Downloads*.
 ** Click *Software*.
 ** Find your management software (for example, SANtricity System Manager), and then click *Go!* on the right.
 ** Click *View & Download* on the latest version.
 ** Click *Continue* at the bottom of the page.
 ** Accept the EULA.
 ** Scroll down until you see *MIB file for SNMP traps*, and then click the link to download the file.

.Steps

. Select *Settings* > *Alerts*.
. Select the *SNMP* tab.
+
The currently defined trap destinations appear in the table.

. Select *Add Trap Desinations*.
+
The Add Trap Destinations dialog box opens.

. Enter one or more trap destinations, select their associated community names, and then click *Add*.
 ** *Trap Destination* -- Enter an IPv4 or IPv6 address of the server running an SNMP service.
 ** *Community name* -- From the drop-down, select the community name for this trap destination. (If you defined only one community name, the name already appears in this field.)
 ** *Send Authentication Failure Trap* -- Select this option (the checkbox) if you want to alert the trap destination whenever an SNMP request is rejected because of an unrecognized community name.
After you click *Add*, the trap destinations and associated community names appear in the table.
. To make sure a trap is valid, select a trap destination from the table, and then click *Test Trap Destination* to send a test trap to the configured address.

.Results

The event monitor sends SNMP traps to the server(s) whenever an alertable event occurs.
