---
permalink: sm-settings/task_step_3_import_signed_certificates_for_the_controllers.html
sidebar: sidebar
keywords: 
summary: 'After you receive signed certificates, you import the files for the controllers.'
---
= Step 2: Import signed certificates for controllers
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
After you receive signed certificates, you import the files for the controllers.

== Before you begin

* The CA returned signed certificate files.
* The files are available on your local system.
* If the CA provided a chained certificate (for example, a .p7b file), you must unpack the chained file into individual files: the root certificate, one or more intermediate certificates, and the server certificates that identify the controllers. You can use the Windows `certmgr` utility to unpack the files (right-click and select menu:All Tasks[Export]). When the exports are complete, a CER file is shown for each certificate file in the chain.

== About this task

This task describes how to upload the certificate files.

== Steps

. Select *Settings* > *Certificates*.
. From the *Array Management* tab, select *Import*.
+
A dialog box opens for importing the certificate file(s).

. Click the *Browse* buttons to first select the root and intermediate files, and then select each server certificate for the controllers. The root and intermediate files are the same for both controllers. Only the server certificates are unique for each controller.
+
The file names are displayed in the dialog box.

. Click *Import*.
+
The file(s) are uploaded and validated.

== Results

The session is automatically terminated. You must log in again for the certificate(s) to take effect. When you log in again, the new CA-signed certificate is used for your session.
