---
permalink: sm-support/collect-drive-data.html
sidebar: sidebar
keywords: 
summary: 'You can collect log data from all drives in your storage array and send the file to technical support for analysis.'
---
= Collect drive data
:icons: font
:imagesdir: ../media/

[.lead]
You can collect log data from all drives in your storage array and send the file to technical support for analysis.

== About this task

Log data consists of statistical information that is maintained by each of the drives in your storage array. Technical support can use this information to analyze the performance of your drives and for troubleshooting problems that might exist.

[NOTE]
====
Perform this operation only when instructed to do so by technical support.
====

== Steps

. Select *Support* > *Support Center* > *Diagnostics* tab.
. Select *Collect Drive Data*.
+
A dialog box appears listing all drives in your storage array.

. In the first column of the table, you can either select individual drives for which you want to collect data (click the check box next to each drive) or select all drives (select the check box in the table header).
+
To find particular drives, you can sort any of the columns or type characters in the *Filter* box.

. Click *Collect*.
+
The file is saved in the Downloads folder for your browser with the name `drive-data.7z`.

. Follow the instructions provided by technical support to send the file to them.
