---
permalink: um-certificates/concept_why_can_t_i_log_in_unified.html
sidebar: sidebar
keywords: 
summary: 'If you receive an error when attempting to log in to SANtricity Unified Manager, review these possible causes.'
---
= Why can't I log in?
:icons: font
:imagesdir: ../media/

[.lead]
If you receive an error when attempting to log in to SANtricity Unified Manager, review these possible causes.

Login errors to Unified Manager might occur for one of these reasons:

* You entered an incorrect username or password.
* You have insufficient privileges.
* The directory server (if configured) might be unavailable. If this is the case, try logging in with a local user role.
* You attempted to log in unsuccessfully multiple times, which triggered the lockout mode. Wait 10 minutes to re-login.

Login errors to a remote storage array for mirroring tasks might occur for one of these reasons:

* You have entered an incorrect password.
* You attempted to log in unsuccessfully multiple times, which triggered the lockout mode. Wait 10 minutes to log in again.
* The maximum number of client connections used on the controller has been reached. Check for multiple users or clients.
