---
permalink: um-certificates/task_step_3_import_management_certificates_unified.html
sidebar: sidebar
keywords: 
summary: 'After you receive signed certificates, import the certificate chain for the host system where the Unified Manager interface is installed.'
---
= Step 2: Import management certificates
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
After you receive signed certificates, import the certificate chain for the host system where the Unified Manager interface is installed.

== Before you begin

* You must be logged in with a user profile that includes Security admin permissions. Otherwise, certificate functions do not appear.
* You have generated a certificate signing request (.CSR file) and sent it to the CA.
* The CA returned trusted certificate files.
* The certificate files are installed on your local system.
* If the CA provided a chained certificate (for example, a .p7b file), you must unpack the chained file into individual files: the root certificate, one or more intermediate certificates, and the server certificate. You can use the Windows `certmgr` utility to unpack the files (right-click and select menu:All Tasks[Export]). When the exports are complete, a CER file is shown for each certificate file in the chain.

== Steps

. Select *Certificate Management*.
. From the *Management* tab, select *Import*.
+
A dialog box opens for importing the certificate files.

. Click *Browse* to first select the root and intermediate files, and then select the server certificate.
+
The filenames are displayed in the dialog box.

. Click *Import*.

== Results

The files are uploaded and validated. The certificate information displays on the Certificate Management page.
